name: Deploy ASP.NET Core app to Azure Web App

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: 'ajs-app-service' # Replace with your app name
  AZURE_STAGING_PUBLISH_PROFILE: 'ajs-demoapp-service-staging'   # Staging URL.
  AZURE_WEBAPP_PACKAGE_PATH: '.' # Set this to the path to your web app project
  DOTNET_VERSION: '9.0.*' # Set this to the .NET Core version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: dotnet build and publish
        run: |
          dotnet build --configuration Release
          dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
      - name: Deploy to Azure Web apps
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
#          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          publish-profile: ${{ secrets.AZURE_STAGING_PUBLISH_PROFILE }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
